trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'
  dotNetCoreVersion: '2.2.103'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(dotNetCoreVersion)'
  inputs:
    version: $(dotNetCoreVersion)

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: 'tests/**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-build --collect "Code Coverage"'

#- script: dotnet test --configuration $(buildConfiguration) --no-build --collect "Code Coverage" --logger trx
#  displayName: 'dotnet test'

#- task: PublishTestResults@2
#  inputs:
#    testResultsFormat: 'VSTest'
#    testResultsFiles: tests/**/*.trx

- script: 'dotnet pack src/FnProject.Fdk/FnProject.Fdk.csproj --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory) --version-suffix=dev-$(Build.BuildNumber)'
  displayName: 'Package'

- task: PublishBuildArtifacts@1
