FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["{FUNCTION_NAME}.csproj", "."]
RUN dotnet restore "{FUNCTION_NAME}.csproj"
COPY . .
RUN dotnet build "{FUNCTION_NAME}.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "{FUNCTION_NAME}.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "{FUNCTION_NAME}.dll"]