FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["{FUNCTION_NAME}.csproj", "."]
RUN dotnet restore "{FUNCTION_NAME}.csproj"
COPY . .
RUN dotnet build "{FUNCTION_NAME}.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "{FUNCTION_NAME}.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "{FUNCTION_NAME}.dll"]
